### ISSUE TITLE
Crashes when updating from #61 to #67

### ISSUE THREAD

**Issue by Philogag** [BukkitFabric/bukkit4fabric#11]
When I update this mod into #67 from curseforge, it cann't start up with my existing world. 
I tried remove all the other mods and plugins, but it still can't work.
But if I remove the Bukkit4Fabric mod, the server can start up successully.

![image](https://user-images.githubusercontent.com/44018455/91654707-b85d0f80-eadd-11ea-8f01-0dfecb7c328d.png)

My Env:
+ jdk1.8.0_221
+ Minecraft Version: 1.16.2
+ fabricloader: Fabric Loader 0.9.2+build.206
+ fabric: Fabric API 0.19.0+build.398-1.16

Here is the full crash report.
[crash-2020-08-30_16.27.03-server.txt](https://github.com/BukkitFabric/bukkit4fabric/files/5146496/crash-2020-08-30_16.27.03-server.txt)

**Comment by IsaiahPatton** [comment]
Should be fixed in build 78
