### ISSUE TITLE
About what time should this be done

### ISSUE THREAD

**Issue by QPCrummer** [BukkitFabric/bukkit4fabric#13]
Currently we do not support CraftBukkit's net.minecraft.server classes. This is planned to change at a future date.
------------------------------------------------------------------------------------------------------------

I really could use something like this on my server. I'm trying to run GeyserMC and Floodgate on it, however, floodgate depends on the server classes thingy. No rush.

**Comment by QPCrummer** [comment]
Can someone please respond to this. I would recommend this plugin to everyone if the server classes. I do feel like I am being ignored though. All you have to say is that it won't be done for a long, long time (👍

**Comment by IsaiahPatton** [comment]
Currently direct access to those classes will work, but I need to learn how to use ASM to support reflection calls.

**Comment by IsaiahPatton** [comment]
Added support in https://github.com/BukkitFabric/bukkit4fabric/commit/9a4b66fd4de3c542f0b4f13d63a0386d031891a1
