### ISSUE TITLE
CoreProtect (1.16.2) doesn't work (An internal error has occurred).

### ISSUE THREAD

**Issue by Gryzle** [BukkitFabric/bukkit4fabric#14]
One of the most useful spigot/bukkit plugins, "CoreProtect", does not seem to work.

https://www.spigotmc.org/resources/coreprotect.8631/

Thanks! I appreciate your work!

**Comment by IsaiahPatton** [comment]
Fixed in build 70

**Comment by Gryzle** [comment]
Thank you so much!
