### ISSUE TITLE
Very Bad Bug

### ISSUE THREAD

**Issue by QPCrummer** [BukkitFabric/bukkit4fabric#18]
Crashes everytime you go into a furnace or blast furnace. Makes them into ticking entities.
Crash Report:

[crash-2020-09-06_12.29.29-server.txt](https://github.com/BukkitFabric/bukkit4fabric/files/5179960/crash-2020-09-06_12.29.29-server.txt)

**Comment by ZombieNW** [comment]
I had the same problem, completely crashed the server every time someone came near or logged in. Had to spend a long time fixing damages.

**Comment by IsaiahPatton** [comment]
Should be fixed in build 78
