### ISSUE TITLE
Incompatable with lithium

### ISSUE THREAD

**Issue by BuyMyMojo** [BukkitFabric/bukkit4fabric#2]
I get this error when using wiith my lithium server

> [19:58:57] [main/FATAL]: Mixin apply failed lithium.mixins.json:entity.data_tracker.use_arrays.DataTrackerMixin -> net.minecraft.class_2945: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException PRIVATE @Overwrite method method_12783 in lithium.mixins.json:entity.data_tracker.use_arrays.DataTrackerMixin cannot reduce visibiliy of PUBLIC target method
> org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: PRIVATE @Overwrite method method_12783 in lithium.mixins.json:entity.data_tracker.use_arrays.DataTrackerMixin cannot reduce visibiliy of PUBLIC target method
>         at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.conformVisibility(MixinPreProcessorStandard.java:466) ~[fabric-server-launch.jar:?]
>         at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachSpecialMethod(MixinPreProcessorStandard.java:439) ~[fabric-server-launch.jar:?]
>         at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachOverwriteMethod(MixinPreProcessorStandard.java:403) ~[fabric-server-launch.jar:?]
>         at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachMethods(MixinPreProcessorStandard.java:333) ~[fabric-server-launch.jar:?]
>         at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:286) ~[fabric-server-launch.jar:?]
>         at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:264) ~[fabric-server-launch.jar:?]
>         at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1272) ~[fabric-server-launch.jar:?]
>         at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:287) ~[fabric-server-launch.jar:?]
>         at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345) ~[fabric-server-launch.jar:?]
>         at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:570) [fabric-server-launch.jar:?]
>         at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351) [fabric-server-launch.jar:?]
>         at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191) [fabric-server-launch.jar:?]
>         at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) [fabric-server-launch.jar:?]
>         at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23) [fabric-server-launch.jar:?]
>         at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157) [fabric-server-launch.jar:?]
>         at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143) [fabric-server-launch.jar:?]
>         at java.lang.ClassLoader.loadClass(Unknown Source) [?:1.8.0_251]
>         at net.minecraft.class_1297.<clinit>(class_1297.java:199) [intermediary-server.jar:?]
>         at net.minecraft.class_5135.<clinit>(class_5135.java:76) [intermediary-server.jar:?]
>         at net.minecraft.class_2966.method_17598(class_2966.java:109) [intermediary-server.jar:?]
>         at net.minecraft.server.Main.main(Main.java:90) [intermediary-server.jar:?]
>         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_251]
>         at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
>         at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_251]
>         at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192) [fabric-server-launch.jar:?]
>         at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140) [fabric-server-launch.jar:?]
>         at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:26) [fabric-server-launch.jar:?]
>         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_251]
>         at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
>         at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_251]
>         at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:61) [fabric-server-launch.jar:?]
>         at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:105) [fabric-server-launch.jar:?]
>         at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:49) [fabric-server-launch.jar:?]
> [19:58:57] [main/INFO]: [STDERR]: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [lithium.mixins.json:entity.data_tracker.use_arrays.DataTrackerMixin] from phase [DEFAULT] in config [lithium.mixins.json] FAILED during APPLY
> [19:58:57] [main/INFO]: [STDERR]:       at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:643)
> [19:58:57] [main/INFO]: [STDERR]:       at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:595)
> [19:58:57] [main/INFO]: [STDERR]:       at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:356)
> [19:58:57] [main/INFO]: [STDERR]:       at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191)
> [19:58:57] [main/INFO]: [STDERR]:       at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
> [19:58:57] [main/INFO]: [STDERR]:       at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
> [19:58:57] [main/INFO]: [STDERR]:       at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
> [19:58:57] [main/INFO]: [STDERR]:       at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143)
> [19:58:57] [main/INFO]: [STDERR]:       at java.lang.ClassLoader.loadClass(Unknown Source)
> [19:58:57] [main/INFO]: [STDERR]:       at net.minecraft.class_1297.<clinit>(class_1297.java:199)
> [19:58:57] [main/INFO]: [STDERR]:       at net.minecraft.class_5135.<clinit>(class_5135.java:76)
> [19:58:57] [main/INFO]: [STDERR]:       at net.minecraft.class_2966.method_17598(class_2966.java:109)
> [19:58:57] [main/INFO]: [STDERR]:       at net.minecraft.server.Main.main(Main.java:90)
> [19:58:57] [main/INFO]: [STDERR]:       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> [19:58:57] [main/INFO]: [STDERR]:       at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> [19:58:57] [main/INFO]: [STDERR]:       at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> [19:58:57] [main/INFO]: [STDERR]:       at java.lang.reflect.Method.invoke(Unknown Source)
> [19:58:57] [main/INFO]: [STDERR]:       at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
> [19:58:57] [main/INFO]: [STDERR]:       at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
> [19:58:57] [main/INFO]: [STDERR]:       at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:26)
> [19:58:57] [main/INFO]: [STDERR]:       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> [19:58:57] [main/INFO]: [STDERR]:       at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> [19:58:57] [main/INFO]: [STDERR]:       at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> [19:58:57] [main/INFO]: [STDERR]:       at java.lang.reflect.Method.invoke(Unknown Source)
> [19:58:57] [main/INFO]: [STDERR]:       at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:61)
> [19:58:57] [main/INFO]: [STDERR]:       at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:105)
> [19:58:57] [main/INFO]: [STDERR]:       at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:49)
> [19:58:57] [main/INFO]: [STDERR]: Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: PRIVATE @Overwrite method method_12783 in lithium.mixins.json:entity.data_tracker.use_arrays.DataTrackerMixin cannot reduce visibiliy of PUBLIC target method
> [19:58:57] [main/INFO]: [STDERR]:       at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.conformVisibility(MixinPreProcessorStandard.java:466)
> [19:58:57] [main/INFO]: [STDERR]:       at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachSpecialMethod(MixinPreProcessorStandard.java:439)
> [19:58:57] [main/INFO]: [STDERR]:       at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachOverwriteMethod(MixinPreProcessorStandard.java:403)
> [19:58:57] [main/INFO]: [STDERR]:       at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachMethods(MixinPreProcessorStandard.java:333)
> [19:58:57] [main/INFO]: [STDERR]:       at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:286)
> [19:58:57] [main/INFO]: [STDERR]:       at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:264)
> [19:58:57] [main/INFO]: [STDERR]:       at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1272)
> [19:58:57] [main/INFO]: [STDERR]:       at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:287)
> [19:58:57] [main/INFO]: [STDERR]:       at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
> [19:58:57] [main/INFO]: [STDERR]:       at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:570)
> [19:58:57] [main/INFO]: [STDERR]:       at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
> [19:58:57] [main/INFO]: [STDERR]:       ... 24 more
> Exception in thread "main" [19:58:57] [main/INFO]: [STDERR]: java.lang.RuntimeException: Failed to setup Fabric server environment!
> [19:58:57] [main/INFO]: [STDERR]:       at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:51)
> [19:58:57] [main/INFO]: [STDERR]: Caused by: java.lang.RuntimeException: java.lang.RuntimeException: An exception occurred when launching the server!
> [19:58:57] [main/INFO]: [STDERR]:       at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:107)
> [19:58:57] [main/INFO]: [STDERR]:       at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:49)
> [19:58:57] [main/INFO]: [STDERR]: Caused by: java.lang.RuntimeException: An exception occurred when launching the server!
> [19:58:57] [main/INFO]: [STDERR]:       at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:63)
> [19:58:57] [main/INFO]: [STDERR]:       at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:105)
> [19:58:57] [main/INFO]: [STDERR]:       ... 1 more
> [19:58:57] [main/INFO]: [STDERR]: Caused by: java.lang.reflect.InvocationTargetException
> [19:58:57] [main/INFO]: [STDERR]:       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> [19:58:57] [main/INFO]: [STDERR]:       at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> [19:58:57] [main/INFO]: [STDERR]:       at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> [19:58:57] [main/INFO]: [STDERR]:       at java.lang.reflect.Method.invoke(Unknown Source)
> [19:58:57] [main/INFO]: [STDERR]:       at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:61)
> [19:58:57] [main/INFO]: [STDERR]:       ... 2 more
> [19:58:57] [main/INFO]: [STDERR]: Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
> [19:58:57] [main/INFO]: [STDERR]:       at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:194)
> [19:58:57] [main/INFO]: [STDERR]:       at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
> [19:58:57] [main/INFO]: [STDERR]:       at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:26)
> [19:58:57] [main/INFO]: [STDERR]:       ... 7 more
> [19:58:57] [main/INFO]: [STDERR]: Caused by: java.lang.reflect.InvocationTargetException
> [19:58:57] [main/INFO]: [STDERR]:       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> [19:58:57] [main/INFO]: [STDERR]:       at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> [19:58:57] [main/INFO]: [STDERR]:       at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> [19:58:57] [main/INFO]: [STDERR]:       at java.lang.reflect.Method.invoke(Unknown Source)
> [19:58:57] [main/INFO]: [STDERR]:       at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
> [19:58:57] [main/INFO]: [STDERR]:       ... 9 more
> [19:58:57] [main/INFO]: [STDERR]: Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
> [19:58:57] [main/INFO]: [STDERR]:       at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:364)
> [19:58:57] [main/INFO]: [STDERR]:       at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191)
> [19:58:57] [main/INFO]: [STDERR]:       at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
> [19:58:57] [main/INFO]: [STDERR]:       at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
> [19:58:57] [main/INFO]: [STDERR]:       at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
> [19:58:57] [main/INFO]: [STDERR]:       at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143)
> [19:58:57] [main/INFO]: [STDERR]:       at java.lang.ClassLoader.loadClass(Unknown Source)
> [19:58:57] [main/INFO]: [STDERR]:       at net.minecraft.class_1297.<clinit>(class_1297.java:199)
> [19:58:57] [main/INFO]: [STDERR]:       at net.minecraft.class_5135.<clinit>(class_5135.java:76)
> [19:58:57] [main/INFO]: [STDERR]:       at net.minecraft.class_2966.method_17598(class_2966.java:109)
> [19:58:57] [main/INFO]: [STDERR]:       at net.minecraft.server.Main.main(Main.java:90)
> [19:58:57] [main/INFO]: [STDERR]:       ... 14 more
> [19:58:57] [main/INFO]: [STDERR]: Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [lithium.mixins.json:entity.data_tracker.use_arrays.DataTrackerMixin] from phase [DEFAULT] in config [lithium.mixins.json] FAILED during APPLY
> [19:58:57] [main/INFO]: [STDERR]:       at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:643)
> [19:58:57] [main/INFO]: [STDERR]:       at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:595)
> [19:58:57] [main/INFO]: [STDERR]:       at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:356)
> [19:58:57] [main/INFO]: [STDERR]:       ... 24 more
> [19:58:57] [main/INFO]: [STDERR]: Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: PRIVATE @Overwrite method method_12783 in lithium.mixins.json:entity.data_tracker.use_arrays.DataTrackerMixin cannot reduce visibiliy of PUBLIC target method
> [19:58:57] [main/INFO]: [STDERR]:       at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.conformVisibility(MixinPreProcessorStandard.java:466)
> [19:58:57] [main/INFO]: [STDERR]:       at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachSpecialMethod(MixinPreProcessorStandard.java:439)
> [19:58:57] [main/INFO]: [STDERR]:       at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachOverwriteMethod(MixinPreProcessorStandard.java:403)
> [19:58:57] [main/INFO]: [STDERR]:       at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachMethods(MixinPreProcessorStandard.java:333)
> [19:58:57] [main/INFO]: [STDERR]:       at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:286)
> [19:58:57] [main/INFO]: [STDERR]:       at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:264)
> [19:58:57] [main/INFO]: [STDERR]:       at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1272)
> [19:58:57] [main/INFO]: [STDERR]:       at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:287)
> [19:58:57] [main/INFO]: [STDERR]:       at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
> [19:58:57] [main/INFO]: [STDERR]:       at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:570)
> [19:58:57] [main/INFO]: [STDERR]:       at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
> [19:58:57] [main/INFO]: [STDERR]:       ... 24 more

**Comment by IsaiahPatton** [comment]
fixed
