### ISSUE TITLE
get stuck in word loading at 100%

### ISSUE THREAD

**Issue by DerHofnarr** [BukkitFabric/bukkit4fabric#22]
Like the title says lol. I downloaded and installed the mod (with other mods and plugins) and i got stucked in the word loading menu at 100% for a big amount of time. :D 

i did verified that it was Bukkit4Fabric mod and no other mods. Maybe someone can help me fix the problem because i really want to use plugins. 

Cheers :-)

**Comment by IsaiahPatton** [comment]
Due to how Bukkit is written, running the mod not on a server is not supported.
