### ISSUE TITLE
Bssentials Incompatibilities

### ISSUE THREAD

**Issue by RichardIsSoarx420** [BukkitFabric/bukkit4fabric#24]
/Fly works now with LuckPerms, but /Homes is completely broken. Along with  many commands such as /speed, /enchant, /time set, Etc.
[EssentialsHomesNoListNoTP.txt](https://github.com/BukkitFabric/bukkit4fabric/files/5328361/EssentialsHomesNoListNoTP.txt)

**Comment by IsaiahPatton** [comment]
fixed
