### ISSUE TITLE
Interacting with villagers & job sites causes crashes

### ISSUE THREAD

**Issue by CamoMano** [BukkitFabric/bukkit4fabric#25]
Using job site: https://hastebin.com/hajalohaka.yaml

Interacting with villager: https://hastebin.com/ebiluwered.yaml

**Comment by IsaiahPatton** [comment]
Fixed in https://github.com/BukkitFabric/bukkit4fabric/commit/a5c755256868ea5182d4c16b0a37e226df62d458 & https://github.com/BukkitFabric/bukkit4fabric/commit/662ec4d7dbb1d11862b3d330960d63180e0a952d
