### ISSUE TITLE
Detected stop event: java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by Grayseon** [BukkitFabric/bukkit4fabric#265]
I am using a 1GB server to run Fabric and the Cardboard mod. When I start up the server with the latest Cardboard update, the server crashes giving this error: Detected stop event: java.lang.OutOfMemoryError: Java heap space . The crash report file is attached:
[crash-2021-09-19_12.56.29-server.txt](https://github.com/CardboardPowered/cardboard/files/7192131/crash-2021-09-19_12.56.29-server.txt)

**Comment by L0rdLogan** [comment]
Nothing to do with cardboard

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Grayseon ***@***.***>
Sent: Sunday, September 19, 2021 2:10:07 PM
To: CardboardPowered/cardboard ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [CardboardPowered/cardboard] Detected stop event: java.lang.OutOfMemoryError: Java heap space (#265)


I am using a 1GB server to run Fabric and the Cardboard mod. When I start up the server with the latest Cardboard update, the server crashes giving this error: Detected stop event: java.lang.OutOfMemoryError: Java heap space . The crash report file is attached:
crash-2021-09-19_12.56.29-server.txt<https://github.com/CardboardPowered/cardboard/files/7192131/crash-2021-09-19_12.56.29-server.txt>

**Comment by Grayseon** [comment]
Thank you for the reply, is it the small amount of memory? I have no other mods enabled.

**Comment by L0rdLogan** [comment]
Don’t get me wrong it’s an interesting one, the minimum amount of ram I use with a modded server is 4GB, I’ve never tried any lower

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
