### ISSUE TITLE
Can't use Essentials

### ISSUE THREAD

**Issue by Light-FD** [BukkitFabric/bukkit4fabric#28]
I use this mod on 1.16.3 and I can't join my server
[error.txt](https://github.com/BukkitFabric/bukkit4fabric/files/5359600/error.txt)

**Comment by CamoMano** [comment]
What version of essentials?

**Comment by Light-FD** [comment]
> What version of essentials?

The latest version(2.18.1)

**Comment by IsaiahPatton** [comment]
Does the ops.json file exist, because it cannot find it.

**Comment by Light-FD** [comment]
Of course it exist

**Comment by IsaiahPatton** [comment]
try the latest build, should be fixed now.
