### ISSUE TITLE
Server crash on startup

### ISSUE THREAD

**Issue by DJTobi1Kenobi** [BukkitFabric/bukkit4fabric#29]
I cannot get my server to load when this mod is installed, the following shows up in my cmd log (This has more data than my crash log hence why I have included this instead, I have crash log if wanted):

https://paste.enginehub.org/DxGh3ahnp

**Comment by EnderBro123** [comment]
Also have a crash.
https://pastebin.com/sPQZHSj8

**Comment by QPCrummer** [comment]
This is a problem. It makes this mod useless right now. Has something to do with the recipe manager mixin.

**Comment by QPCrummer** [comment]
Release 96 is the latest working one.

**Comment by IsaiahPatton** [comment]
should be fixed in https://github.com/BukkitFabric/bukkit4fabric/commit/1b232da0b27f512a9974a9bc6ffb87d7428f3298
