### ISSUE TITLE
Crash.

### ISSUE THREAD

**Issue by EnderBro123** [BukkitFabric/bukkit4fabric#30]
https://pastebin.com/sPQZHSj8

No crash report is given. Just this.

**Comment by QPCrummer** [comment]
I think it has something to do with the RecipeManagerMixin. 

main/FATAL Mixin apply failed bukkitfabric.mixins.json:recipe.MixinRecipeManager -> net.minecraft.class_1863: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException PROTECTED @Overwrite method method_20705 in bukkitfabric.mixins.json:recipe.MixinRecipeManager cannot reduce visibiliy of PUBLIC target method

**Comment by QPCrummer** [comment]
Maybe use the 98 release?

**Comment by QPCrummer** [comment]
Release 96 is the latest working one.

**Comment by IsaiahPatton** [comment]
Fixed in commit https://github.com/BukkitFabric/bukkit4fabric/commit/1b232da0b27f512a9974a9bc6ffb87d7428f3298

**Comment by EnderBro123** [comment]
Great. Thank you.

**Comment by EnderBro123** [comment]
@IsaiahPatton Tried both the dev build and build on Curse. Same crash.

https://pastebin.com/7bjnYNB9
