### ISSUE TITLE
Cardboard won't let the server start

### ISSUE THREAD

**Issue by loustact** [BukkitFabric/bukkit4fabric#307]
Hello! So, I was starting the server, but Cardboard won't let it because it "requires any version of fabric, which is missing!" according to the log. I'm not really sure what I'm dealing with but please help.

FYI, I'm using Fabric 1.18.1, with mods used are Lithium, Phosphor, and iCommonLib. I'm also running the server under FalixNode.

Here's the log file
[latest.log](https://github.com/CardboardPowered/cardboard/files/7776469/latest.log)

**Comment by jordi04** [comment]
I have the exact same problem, im also running lithium, phosphor and icommonlib with fabric API

**Comment by pisaiah** [comment]
> requires any version of fabric, which is missing!

Install Fabric API, [https://www.curseforge.com/minecraft/mc-mods/fabric-api](https://www.curseforge.com/minecraft/mc-mods/fabric-api)

**Comment by loustact** [comment]
nevermind i forgot to install it. thatnks for the help
