### ISSUE TITLE
Flicking a lever while holding a block places the block and flicks the lever.

### ISSUE THREAD

**Issue by ThatGamerBlue** [BukkitFabric/bukkit4fabric#33]
Block placement shouldn't happen when targeting a lever. Probably happens with other stuff like buttons/repeaters/comparators/etc too

**Comment by IsaiahPatton** [comment]
Fixed in https://github.com/BukkitFabric/bukkit4fabric/commit/b4f3d2f048edbf3dcee996958561c5ca573060a5
