### ISSUE TITLE
Tried both the latest dev build and latest build on Curse. Same crash.

### ISSUE THREAD

**Issue by EnderBro123** [BukkitFabric/bukkit4fabric#34]
@IsaiahPatton Tried both the latest dev build and latest build on Curse. Same crash.

https://pastebin.com/7bjnYNB9

_Originally posted by @EnderBro123 in https://github.com/BukkitFabric/bukkit4fabric/issue_comments/708567073_

**Comment by arceuss** [comment]
same here

**Comment by IsaiahPatton** [comment]
Was fixed in https://github.com/BukkitFabric/bukkit4fabric/commit/1b232da0b27f512a9974a9bc6ffb87d7428f3298
