### ISSUE TITLE
Incompatible with Cloth and Fabric API due to mixin overwrites

### ISSUE THREAD

**Issue by MaxNeedsSnacks** [BukkitFabric/bukkit4fabric#35]
Log files:
[Cloth crashing (2020-10-18-7.log)](https://github.com/BukkitFabric/bukkit4fabric/files/5398094/2020-10-18-7.log)
[Fabric API crashing (latest.log)](https://github.com/BukkitFabric/bukkit4fabric/files/5398095/latest.log)

Both of these crashes occur because of `@​Overwrite` being used [here](https://github.com/BukkitFabric/bukkit4fabric/blob/master/src/main/java/com/javazilla/bukkitfabric/mixin/entity/MixinItemEntity.java#L46) and [here](https://github.com/BukkitFabric/bukkit4fabric/blob/master/src/main/java/com/javazilla/bukkitfabric/mixin/item/MixinItemStack.java#L29), respectively (in the second one, L54 also breaks obviously).

As both of these seem to merely exist to post events with Bukkit, neither of these two methods ***should*** actually be overwritten. A much better practice would be to use `@Inject` or `@Redirect`, respectively. I'm not entirely sure whether these two are the only instances of `@Overwrite` being used where it shouldn't be, but in general, overwriting methods breaks compatibility with a whole set of mods whenever used and should thus generally be avoided if you can ^^

**Comment by MaxNeedsSnacks** [comment]
Another rather important thing: Please don't use double-casts in places like this
https://github.com/BukkitFabric/bukkit4fabric/blob/35dc3ede8be02e20c59a22be2a922ded9272391b/src/main/java/com/javazilla/bukkitfabric/mixin/item/MixinItemStack.java#L57
You should rather make the mixin an abstract class and then `@Shadow` existing fields and methods, so something like
```java
@Shadow
private abstract Object something;
```

**Comment by IsaiahPatton** [comment]
fixed in https://github.com/BukkitFabric/bukkit4fabric/commit/f1ef16d2ae23c400274773f13d1d57b886445c54
