### ISSUE TITLE
server won't start gives error 1.18.2

### ISSUE THREAD

**Issue by Skywalker8510** [BukkitFabric/bukkit4fabric#353]
the mods I have installed are 
fabric API
geyser fabric
floodgate fabric
fabric carpet mod
carpet fixes
lithium 
starlight
icommon
and cardboard

everything works fine if I get rid of cardboard

this is the crash I get

<html>NoSuchMethodError:<br>'net.kyori.adventure.util.Codec net.kyori.adventure.util.Codec.codec(net.kyori.adventure.util.Codec$Decoder, net.kyori.adventure.util.Codec$Encoder)'</html>
<html>at net.kyori.adventure.platform.fabric.impl.NBTLegacyHoverEventSerializer.&lt;clinit&gt;(NBTLegacyHoverEventSerializer.java:43)<br>at net.kyori.adventure.platform.fabric.impl.service.GsonComponentSerializerProviderImpl.lambda$builder$0(GsonComponentSerializerProviderImpl.java:50)<br>at net.kyori.adventure.text.serializer.gson.GsonComponentSerializerImpl$BuilderImpl.&lt;init&gt;(GsonComponentSerializerImpl.java:117)<br>at net.kyori.adventure.text.serializer.gson.GsonComponentSerializer.builder(GsonComponentSerializer.java:77)<br>at net.kyori.adventure.platform.fabric.impl.service.GsonComponentSerializerProviderImpl.gson(GsonComponentSerializerProviderImpl.java:34)<br>at java.base/java.util.Optional.map(Optional.java:260)<br>at net.kyori.adventure.text.serializer.gson.GsonComponentSerializerImpl$Instances.&lt;clinit&gt;(GsonComponentSerializerImpl.java:48)<br>at net.kyori.adventure.text.serializer.gson.GsonComponentSerializer.gson(GsonComponentSerializer.java:54)<br>at net.minecraft.class_2561$class_2562.handler$zzb000$adventure$injectGson(class_2561.java:1064)<br>at net.minecraft.class_2561$class_2562.method_10878(class_2561.java:133)<br>at net.minecraft.class_156.method_656(class_156.java:430)<br>at net.minecraft.class_2561$class_2562.&lt;clinit&gt;(class_2561.java:131)<br>at net.minecraft.class_1799.method_7977(class_1799.java:638)<br>at net.minecraft.class_3765.method_16515(class_3765.java:702)<br>at net.minecraft.class_3763.&lt;clinit&gt;(class_3763.java:50)<br>at net.minecraft.class_5135.&lt;clinit&gt;(class_5135.java:98)<br>at net.minecraft.class_2966.method_17598(class_2966.java:137)<br>at net.minecraft.server.Main.main(Main.java:99)<br>at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)<br>at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)<br>at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23)<br>at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69)<br>at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69)</html>

**Comment by someone1995** [comment]
Try getting rid of Carpet for testing.
