### ISSUE TITLE
Crash with latest version!

### ISSUE THREAD

**Issue by QPCrummer** [BukkitFabric/bukkit4fabric#37]
I don't code, but I know something isn't working. The only mods I had on my server was Fabric API and this.

19.10 19:47:59 [Server] main/FATAL Mixin apply failed fabric-item-api-v1.mixins.json:ItemStackMixin -> net.minecraft.class_1799: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException @At("INVOKE") on net/minecraft/class_1799::hookDamage with priority 1000 cannot inject into net/minecraft/class_1799::method_7956(ILnet/minecraft/class_1309;Ljava/util/function/Consumer;)V merged by com.javazilla.bukkitfabric.mixin.item.MixinItemStack with priority 1000 [PREINJECT Applicator Phase -> fabric-item-api-v1.mixins.json:ItemStackMixin -> Prepare Injections ->  -> modify$zdb000$hookDamage(I)I -> Prepare]
19.10 19:47:59 [Server] INFO org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("INVOKE") on net/minecraft/class_1799::hookDamage with priority 1000 cannot inject into net/minecraft/class_1799::method_7956(ILnet/minecraft/class_1309;Ljava/util/function/Consumer;)V merged by com.javazilla.bukkitfabric.mixin.item.MixinItemStack with priority 1000 [PREINJECT Applicator Phase -> fabric-item-api-v1.mixins.json:ItemStackMixin -> Prepare Injections ->  -> modify$zdb000$hookDamage(I)I -> Prepare]
19.10 19:47:59 [Server] INFO at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:293) ~[fabric_1.16.3.jar:?]
19.10 19:47:59 [Server] INFO at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240) ~[fabric_1.16.3.jar:?]
19.10 19:47:59 [Server] INFO at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:375) ~[fabric_1.16.3.jar:?]
19.10 19:47:59 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1255) ~[fabric_1.16.3.jar:?]
19.10 19:47:59 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1033) ~[fabric_1.16.3.jar:?]
19.10 19:47:59 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:388) ~[fabric_1.16.3.jar:?]
19.10 19:47:59 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320) ~[fabric_1.16.3.jar:?]
19.10 19:47:59 [Server] INFO at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345) ~[fabric_1.16.3.jar:?]
19.10 19:47:59 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569) ~[fabric_1.16.3.jar:?]
19.10 19:47:59 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351) ~[fabric_1.16.3.jar:?]
19.10 19:47:59 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208) ~[fabric_1.16.3.jar:?]
19.10 19:47:59 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) ~[fabric_1.16.3.jar:?]
19.10 19:47:59 [Server] INFO at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23) ~[fabric_1.16.3.jar:?]
19.10 19:47:59 [Server] INFO at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157) ~[fabric_1.16.3.jar:?]
19.10 19:47:59 [Server] INFO at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:148) ~[fabric_1.16.3.jar:?]
19.10 19:47:59 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_262]
19.10 19:47:59 [Server] INFO at net.minecraft.class_1761.<init>(class_1761.java:115) ~[intermediary-server.jar:?]
19.10 19:47:59 [Server] INFO at net.minecraft.class_1761$1.<init>(class_1761.java:16) ~[intermediary-server.jar:?]
19.10 19:47:59 [Server] INFO at net.minecraft.class_1761.<clinit>(class_1761.java:16) ~[intermediary-server.jar:?]
19.10 19:47:59 [Server] INFO at net.minecraft.class_1802.<clinit>(class_1802.java:18) ~[intermediary-server.jar:?]
19.10 19:47:59 [Server] INFO at net.minecraft.class_2378.method_10234(class_2378.java:158) ~[intermediary-server.jar:?]
19.10 19:47:59 [Server] INFO at net.minecraft.class_2378.method_29110(class_2378.java:246) ~[intermediary-server.jar:?]
19.10 19:47:59 [Server] INFO at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684) [?:1.8.0_262]
19.10 19:47:59 [Server] INFO at net.minecraft.class_2378.<clinit>(class_2378.java:245) [intermediary-server.jar:?]
19.10 19:47:59 [Server] INFO at net.minecraft.class_2966.method_12851(class_2966.java:42) [intermediary-server.jar:?]
19.10 19:47:59 [Server] INFO at net.minecraft.server.Main.main(Main.java:88) [intermediary-server.jar:?]
19.10 19:47:59 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_262]
19.10 19:47:59 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_262]

**Comment by QPCrummer** [comment]
Also, it is incompatible with Gnembon's Carpet mod still. 

19.10 19:57:28 [Server] main/WARN @Mixin target net/minecraft/class_3898$class_3208 is public in fabric-networking-v0.mixins.json:MixinEntityTracker and should be specified in value
19.10 19:57:32 [Server] main/FATAL Mixin apply failed fabric-item-api-v1.mixins.json:ItemStackMixin -> net.minecraft.class_1799: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException @At("INVOKE") on net/minecraft/class_1799::hookDamage with priority 1000 cannot inject into net/minecraft/class_1799::method_7956(ILnet/minecraft/class_1309;Ljava/util/function/Consumer;)V merged by com.javazilla.bukkitfabric.mixin.item.MixinItemStack with priority 1000 [PREINJECT Applicator Phase -> fabric-item-api-v1.mixins.json:ItemStackMixin -> Prepare Injections ->  -> modify$zdj000$hookDamage(I)I -> Prepare]
19.10 19:57:32 [Server] INFO org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("INVOKE") on net/minecraft/class_1799::hookDamage with priority 1000 cannot inject into net/minecraft/class_1799::method_7956(ILnet/minecraft/class_1309;Ljava/util/function/Consumer;)V merged by com.javazilla.bukkitfabric.mixin.item.MixinItemStack with priority 1000 [PREINJECT Applicator Phase -> fabric-item-api-v1.mixins.json:ItemStackMixin -> Prepare Injections ->  -> modify$zdj000$hookDamage(I)I -> Prepare]
19.10 19:57:32 [Server] INFO at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:293) ~[fabric_1.16.3.jar:?]
19.10 19:57:32 [Server] INFO at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240) ~[fabric_1.16.3.jar:?]
19.10 19:57:32 [Server] INFO at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:375) ~[fabric_1.16.3.jar:?]
19.10 19:57:32 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1255) ~[fabric_1.16.3.jar:?]
19.10 19:57:32 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1033) ~[fabric_1.16.3.jar:?]
19.10 19:57:32 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:388) ~[fabric_1.16.3.jar:?]
19.10 19:57:32 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320) ~[fabric_1.16.3.jar:?]
19.10 19:57:32 [Server] INFO at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345) ~[fabric_1.16.3.jar:?]
19.10 19:57:32 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569) ~[fabric_1.16.3.jar:?]
19.10 19:57:32 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351) ~[fabric_1.16.3.jar:?]
19.10 19:57:32 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208) ~[fabric_1.16.3.jar:?]
19.10 19:57:32 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) ~[fabric_1.16.3.jar:?]
19.10 19:57:32 [Server] INFO at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23) ~[fabric_1.16.3.jar:?]
19.10 19:57:32 [Server] INFO at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157) ~[fabric_1.16.3.jar:?]
19.10 19:57:32 [Server] INFO at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:148) ~[fabric_1.16.3.jar:?]
19.10 19:57:32 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_262]
19.10 19:57:32 [Server] INFO at net.minecraft.class_1761.<init>(class_1761.java:115) ~[intermediary-server.jar:?]
19.10 19:57:32 [Server] INFO at net.minecraft.class_1761$1.<init>(class_1761.java:16) ~[intermediary-server.jar:?]
19.10 19:57:32 [Server] INFO at net.minecraft.class_1761.<clinit>(class_1761.java:16) ~[intermediary-server.jar:?]
19.10 19:57:32 [Server] INFO at net.minecraft.class_1802.<clinit>(class_1802.java:18) ~[intermediary-server.jar:?]
19.10 19:57:32 [Server] INFO at net.minecraft.class_2378.method_10234(class_2378.java:158) ~[intermediary-server.jar:?]
19.10 19:57:32 [Server] INFO at net.minecraft.class_2378.method_29110(class_2378.java:246) ~[intermediary-server.jar:?]
19.10 19:57:32 [Server] INFO at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684) [?:1.8.0_262]
19.10 19:57:32 [Server] INFO at net.minecraft.class_2378.<clinit>(class_2378.java:245) [intermediary-server.jar:?]
19.10 19:57:32 [Server] INFO at carpet_autocraftingtable.CraftingTableBlockEntity.<clinit>(CraftingTableBlockEntity.java:35) [carpet-autocraftingtable-1.16.3-1.4.11.jar:?]
19.10 19:57:32 [Server] INFO at carpet_autocraftingtable.AutoCraftingTable.<clinit>(AutoCraftingTable.java:11) [carpet-autocraftingtable-1.16.3-1.4.11.jar:?]
19.10 19:57:32 [Server] INFO at net.minecraft.class_128.handler$zhn000$gameStarted(class_128.java:516) [intermediary-server.jar:?]
19.10 19:57:32 [Server] INFO at net.minecraft.class_128.method_24305(class_128.java) [intermediary-server.jar:?]

**Comment by IsaiahPatton** [comment]
Crash with Fabric API fixed in https://github.com/BukkitFabric/bukkit4fabric/commit/f1ef16d2ae23c400274773f13d1d57b886445c54
