### ISSUE TITLE
1.19.4?

### ISSUE THREAD

**Issue by Colorflow-exe** [BukkitFabric/bukkit4fabric#397]
1.19.4 plz

**Comment by samuelh2005** [comment]
It is being worked on, See #362

**Comment by TecEash1** [comment]
Cant wait for 1.19 compact! great work in #362!

**Comment by RichardIsSoarx** [comment]
1.19.4 will be released, once it is announced. And the Developers have time to get around to it. I believe Mouse, is actively working on trying to implement material for 1.20, as it will be vital to how they implement certain events and or / any mixins going forward. @isaiahpatton please close this issue, and mark as RESOLVED.
