### ISSUE TITLE
[NOT ISSUE] discord link invalid

### ISSUE THREAD

**Issue by ghost** [BukkitFabric/bukkit4fabric#416]
Can someone give me valid discord link to discord

**Comment by jonathanjdr** [comment]
It's on their website: [Cardboard - Bukkit4Fabric](https://cardboardpowered.org/)

**Comment by ghost** [comment]
> It's on their website: [Cardboard - Bukkit4Fabric](https://cardboardpowered.org/)

It dosent work

**Comment by L0rdLogan** [comment]
> > It's on their website: [Cardboard - Bukkit4Fabric](https://cardboardpowered.org/)
> 
> 
> 
> It dosent work

https://discord.gg/JqaCNBz4

**Comment by ghost** [comment]
Ty
