### ISSUE TITLE
Hopper Extract - Entity Bukkit Inventory null crash

### ISSUE THREAD

**Issue by MomoAquix** [BukkitFabric/bukkit4fabric#45]
The server crashes when hopper with living animals (like chickens or cows) standing on it. 
[crash-2020-10-27_16.58.14-server.txt](https://github.com/BukkitFabric/bukkit4fabric/files/5444282/crash-2020-10-27_16.58.14-server.txt)

**Comment by IsaiahPatton** [comment]
fixed
