### ISSUE TITLE
Crash at server startup (Using Modpack - 1.20.1 Fabric)

### ISSUE THREAD

**Issue by ayronnnn** [BukkitFabric/bukkit4fabric#459]
Good evening, I have successfully installed Cardboard 1.20 as well as ICommon. However, I believe that one of the mods is preventing Cardboard from functioning properly and therefore causing the server to crash upon launch. Here is the latest.log. I hope you can identify the culprit among the list provided in the logs.

[latest.log](https://github.com/CardboardPowered/cardboard/files/14953161/latest.log)
Thx !

**Comment by ImDefiant** [comment]
The mod Smallships is incompatible with cardboard. There is no fix at the moment.
