### ISSUE TITLE
Duplicated worlds

### ISSUE THREAD

**Issue by Mqxx** [BukkitFabric/bukkit4fabric#462]
Hey, I have installed the Cardboard mod on my test server, and everthing works as expected. But I have one question, since the Fabric server does not split up worlds into overworld, nether and end is there a way to disable this feature from Cardboard, so that I dont have the DIM-1 and DIM1 *and* the split up world the_nether/the_end?

**Comment by ImDefiant** [comment]
The split world folders is just bukkit behavior. Im not sure if data even gets written there with cardboard. Either way they should be harmless. If you want to, for example, reset the nether or end: just delete the split folders and the DIM1 and DIM-1 folders.

**Comment by Mqxx** [comment]
Okay. So what worlds does the server primary use at startup? The split up worlds or the DIM worlds? Or are the split worlds some artifacts that get generated at startup from the DIM worlds by cardboard and then the server uses the DIM worlds?

**Comment by ImDefiant** [comment]
Not really sure to be honest, never really bothered to look into that. You could generate a nether and delete one of the folders and if the nether regenerates or not then you have your answer.

**Comment by pisaiah** [comment]
> Okay. So what worlds does the server primary use at startup? The split up worlds or the DIM worlds? Or are the split worlds some artifacts that get generated at startup from the DIM worlds by cardboard and then the server uses the DIM worlds?

the server should use the DIM worlds. The added folders are just there for plugins that check for them.
