### ISSUE TITLE
Crash at server startup 1.20.1 Fabric

### ISSUE THREAD

**Issue by EsurIItZero** [BukkitFabric/bukkit4fabric#463]
Cardboard has a conflict with [bclig](https://modrinth.com/mod/bclib)

Fix pls 
https://mclo.gs/hscSCsj (latest.log)

**Comment by ImDefiant** [comment]
disable this in the cardboard config: org.cardboardpowered.mixin.item.MixinBoatItem

**Comment by SpencerMSU** [comment]
Hello, I do not understand how to disable them (what should be specifically prescribed)?
# Forcefully Disable Mixins - If a mixin is causing an issue you can disable it here
mixin-force-disable:
	- none
