### ISSUE TITLE
Incompatible with Immersive Portals mod

### ISSUE THREAD

**Issue by DinoTK** [BukkitFabric/bukkit4fabric#47]
Hello!
I tried the **build 118** first, but the server crashed instantly. So, I downloaded the **build 119** and then I managed to open the server, but then it crashed again.
**Crash log**: https://pastebin.com/P9tipkHL
**The mods I have**: https://prnt.sc/v9hveh
**Server RAM**: 8Gb

**Comment by IsaiahPatton** [comment]
#27

**Comment by TwoPointInfinity** [comment]
oop i am sorry, typo.
