### ISSUE TITLE
"[Server thread/WARN]: Exception loading entity" flooding with only Bukkit4Fabric installed latest version

### ISSUE THREAD

**Issue by AugustoResende** [BukkitFabric/bukkit4fabric#48]
Latest jenkins build 119

https://pastebin.com/0MgeHWUJ

**Comment by IsaiahPatton** [comment]
fixed in https://github.com/BukkitFabric/bukkit4fabric/commit/e240940dbf0299b77e5fef334dc0ba339b6358d4
