### ISSUE TITLE
Server Crashes Upon Entry (1.16.3)

### ISSUE THREAD

**Issue by Netra140** [BukkitFabric/bukkit4fabric#58]
When I try to access my server it will crash when I try to get on. It will work initially with all of my plugins and mods perfectly, but after a while something happens in the files that causes logging in to the server to succeed, but immediately kick me out. The command prompt displays what is on crash.txt, and of course the crash log is provided as well. I have the mods: fabric-carpet, carpet-extra, and lithium, and my plugins are: Geyser-Spigot, Multiverse-Core, and Multiverse-Portals. However, I have tested the crash with every combination of these, but it crashes every time. When I start a fresh server with the same world and modifications as my main one, it functions, but eventually starts to crash every time.

[crash-2020-11-09_01.29.00-server.txt](https://github.com/BukkitFabric/bukkit4fabric/files/5508566/crash-2020-11-09_01.29.00-server.txt)

[crash.txt](https://github.com/BukkitFabric/bukkit4fabric/files/5508552/crash.txt)

**Comment by IsaiahPatton** [comment]
fixed
