### ISSUE TITLE
Velocity Proxy Crash

### ISSUE THREAD

**Issue by RawrMaoster** [BukkitFabric/bukkit4fabric#59]
Just wondering. 

Is there any moves to add velocity proxy support? or at least i think that's my issue since my modpack server is fabric and on velocity proxy and not bungeecord.

Heres what im seeing: https://hastebin.com/uqiwacejas.less

Server boots up fine its just when i attempt to join though my test velocity proxy server crashes. both with over 100 mods and with just fabric-api and FabricProxy +Bukkit4Fabric.

Thanks in Advance.
Rawr

**Comment by IsaiahPatton** [comment]
should be fixed now.
