### ISSUE TITLE
Build 124 not Launching

### ISSUE THREAD

**Issue by Kerazene** [BukkitFabric/bukkit4fabric#60]
I have tried to run Bukkit4Fabric-1.16.4.jar in my mods folder, and it does not launch. I receive the error seen in the below pastebin:
https://paste.shockbyte.com/sukaqipabonisitonuci

Bukkit4Fabric is the only mod I have installed - although I have also tried to get this working with the Fabric API. 

I have also tried Bukkit4Fabric build 122, which has worked immediately without any issues. I have not changed anything in my server setup for this to happen, aside from replacing build 124 with build 122.

Sorry if this isn't enough info - first time submitting an issue on here. Let me kn ow if there's any more info I can provide that would help.

Kind Regards,
   Kera

**Comment by Kerazene** [comment]
122 & 125 launch without this issue, this only occurred with 124.

**Comment by IsaiahPatton** [comment]
fixed in 125
