### ISSUE TITLE
EntityRegainHealthEvent causing error during Feature Placement

### ISSUE THREAD

**Issue by Kerazene** [BukkitFabric/bukkit4fabric#61]
Encountering an issue whenever minecraft tries to generate a monument, causing my server to crash every time. Initially this was occuring with multiple mods/plugins enabled, however when removing all mods/plugins the issue persisted. I have been able to replicate this with the following conditions:

**B4F build:** 125

**Mods:**
Bukkit4Fabric
Fabric API

**Plugins:**
_None_

Replication steps:
Create a new world, and travel to a ocean monument, issue will trigger and generate an error similar to this:
https://pastebin.com/LccVv4nB

Seed used in case it's helpful:
7008301453712996954

**Comment by IsaiahPatton** [comment]
fixed in https://github.com/BukkitFabric/bukkit4fabric/commit/e807bdf52bfacc3e80cff75826248605bbc85464
