### ISSUE TITLE
AutoCraftingTable Crash (By Skyrising & Gnembom)

### ISSUE THREAD

**Issue by RichardIsSoarx** [BukkitFabric/bukkit4fabric#63]
When items are pulled from an Autocrafting table via hopper, the game crashes and presents a StackOverFlow error as seen below. I have attached server log and crash report, as well as links to both mods needed to recreate this issue.
https://github.com/gnembon/carpet-autoCraftingTable https://github.com/gnembon/fabric-carpet
https://github.com/gnembon/carpet-autoCraftingTable
Server Log:
[HopperPullFromCraftingTableCrash.txt](https://github.com/BukkitFabric/bukkit4fabric/files/5534809/HopperPullFromCraftingTableCrash.txt)
Crash Report: 
[crash-2020-11-12_22.49.17-server.txt](https://github.com/BukkitFabric/bukkit4fabric/files/5534817/crash-2020-11-12_22.49.17-server.txt)

**Comment by IsaiahPatton** [comment]
fixed in https://github.com/BukkitFabric/bukkit4fabric/commit/1aa191e238d4602e7b9905a2f707c320b0293b03
