### ISSUE TITLE
Unable to open CC: Restitched Computers

### ISSUE THREAD

**Issue by Owningle** [BukkitFabric/bukkit4fabric#70]
The server no longer crashes, however, it still does not allow me to open the computer. It creates an error in the console when i interact with it.

Error: https://pastebin.com/2v8qm18N

**Comment by IsaiahPatton** [comment]
now fixed in https://github.com/BukkitFabric/bukkit4fabric/commit/c9123e1dbc454e76448d0afb27bf83b461235e2c
