### ISSUE TITLE
FactionsUUID is working, but write console error.

### ISSUE THREAD

**Issue by Wr0ngPass** [BukkitFabric/bukkit4fabric#81]
https://hastebin.com/iqitujizar.css

**Comment by IsaiahPatton** [comment]
fixed in https://github.com/BukkitFabric/bukkit4fabric/commit/d3649194604a608ed77925529a18e931a3b4ff52#diff-5c3dd2834326716be001268637d6bea78bea56421a83037515882aa74212b9bfR270
