### ISSUE TITLE
Cannot change blocks with WorldEdit

### ISSUE THREAD

**Issue by kristibektashi** [BukkitFabric/bukkit4fabric#83]
I am completely unable to modify blocks using WorldEdit (bukkit4fabric build 129, latest 1.16.4 fabric server, latest worldedit for 1.16.4 spigot)

**Comment by kristibektashi** [comment]
https://hastebin.com/bedifipaqa.properties

**Comment by IsaiahPatton** [comment]
fixed in https://github.com/BukkitFabric/bukkit4fabric/commit/26e4fd638a2b8fa41e07b9d493b4a0a1b9d46a8b
