### ISSUE TITLE
"DROP STACK TEST" Spam

### ISSUE THREAD

**Issue by richieard** [BukkitFabric/bukkit4fabric#86]
Spamming server logs with test printout. 

https://github.com/BukkitFabric/bukkit4fabric/blob/99c4a48f914b4992f78d7f0f241a6e6602cfe62c/src/main/java/com/javazilla/bukkitfabric/mixin/entity/MixinEntity.java#L279

![31e12f4e23a465a09089424b772a69db](https://user-images.githubusercontent.com/34498981/99925161-05323a00-2d0b-11eb-8264-55833a5aa1b8.png)

**Comment by kristibektashi** [comment]
What does it even mean?

**Comment by IsaiahPatton** [comment]
fixed in https://github.com/BukkitFabric/bukkit4fabric/commit/9f0ab98265d9e0b00d9ac96959c721a264aeab1a
