### ISSUE TITLE
bukkit.yml missing

### ISSUE THREAD

**Issue by kristibektashi** [BukkitFabric/bukkit4fabric#88]
Multiverse-core shows an error because it is missing

I think it should be there so that people can modify options such as allow-end

**Comment by kristibektashi** [comment]
BTW bukkit.yml exists in craftbukkit, spigot and paper

**Comment by IsaiahPatton** [comment]
Fixed in https://github.com/BukkitFabric/bukkit4fabric/commit/c3dc45a92d853610159949d740140482c7d7a9e7
